### ISSUE TITLE
cannot import name FluidSimulation

### ISSUE THREAD

**Issue by thejmazz** [rlguy/GridFluidSim3D#11]
build worked fine, so not sure if I am missing something? 
![image](https://cloud.githubusercontent.com/assets/1270998/17994259/e51559b6-6b24-11e6-8f6d-aafa0f172a3d.png)

In the mean time I can try to use C++, but I'm not too sure how to compile that. What I attempted:

```
g++ example_hello_world.h -o hello-world
```

which gave errors. 

_Edit_ nvm, figured out how to use `main.cpp` :)

**Comment by rlguy** [comment]
Hello thejmazz,

The Python scripts in the examples need to be passed the directory that contains the 'pyfluid' package. This is so that Python knows where to search when importing the package. The pyfluid package is located in the `build/fluidsim/` directory, so the following command should work:

```
python example_hello_world.py ../../../build/fluidsim/
```

It's an easy mistake to make, and you almost had it right. I suppose that the wording in the ImportError message could be unclear and easily misinterpreted, so I'll change it to something better.

Hope this helps!

Best Regards,
Ryan

**Comment by thejmazz** [comment]
ahh that makes sense. cheers!
