### ISSUE TITLE
Python mode?

### ISSUE THREAD

**Issue by enzyme69** [rlguy/GridFluidSim3D#12]
I tried to run this simulation, but I have no knowledge of C and compiling. I tried copy paste the pyfluid folder into Blender and load it inside Blender, but it gives me error.

How to actually run this sims?

**Comment by enzyme69** [comment]
Trying to compile the C++ stuff gives me error also:

```
~/GridFluidSim3D-master/build cmake ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /opt/local/share/cmake-3.7/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler "/usr/bin/cc" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/jimmygunawan/GridFluidSim3D-master/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_2f904/fast"

  xcrun: error: invalid active developer path
  (/Library/Developer/CommandLineTools), missing xcrun at:
  /Library/Developer/CommandLineTools/usr/bin/xcrun

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:12 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/jimmygunawan/GridFluidSim3D-master/build/CMakeFiles/CMakeOutput.log".
See also "/Users/jimmygunawan/GridFluidSim3D-master/build/CMakeFiles/CMakeError.log".
~/GridFluidSim3D-master/build 

```

**Comment by rlguy** [comment]
Hello enzyme69,

This simulator is a separate program from Blender and is not able to be run as a Blender script. The program must be compiled before the Python bindings (pyfluid) can be used. Once built, you will need to write a script to define and run a simulation. Example scripts are located [Here](https://github.com/rlguy/GridFluidSim3D/tree/master/src/examples/python). To use this program with Blender, you will need to write your own methods to export data from Blender and into the simulator.

Knowledge of C/C++ programming helps a lot for debugging compiler errors and using this program, unfortunately. However, I am currently developing a fluid simulation add-on for Blender that handles all of the complicated stuff and does not require building/compiling. Hopefully it will be ready for release within the next few months. The repository will be located [here](https://github.com/rlguy/Blender-FLIP-Fluids-Beta).

I am not exactly sure how to fix the CMake error you are encountering. It looks like it is not able to run the compiler you have installed. This could be caused by CMake or a compiler being installed incorrectly. Or it could be that CMake is trying to use the wrong compiler version. Here is how to set a specific compiler for CMake to use: https://stackoverflow.com/questions/17275348/how-to-specify-new-gcc-path-for-cmake

I hope this helps.

Best Regards,
Ryan
