### ISSUE TITLE
Is it possible to generate particle map instead of meshes?

### ISSUE THREAD

**Issue by magnusviri** [rlguy/GridFluidSim3D#5]
I have been working on Lego particle maps and am wondering if this could output that instead of a mesh.  That is, my meshes are already created and I position them based on particle maps.  The particle maps just have an xyz coordinate for each particle.  I don't know if this makes sense but this simulator should already have that data internally, so it's just a matter of saving that instead of the 3d mesh data.

**Comment by rlguy** [comment]
Hello magnusviri,

Would you be able to clarify further what a particle map is? Would the file be a list of all of the fluid particle positions? For example, if the simulation has particles numbered from `p0` to `pn`, would the data file be in the form: `[p0x, p0y, p0z, p1x, p1y, p1z, ..., pnx, pny, pnz]`?

What form of data would the file output be in? Would the positions be written in binary (such as in 32-bit floating point numbers), or in plain text (written as characters like 3.847472)?

Best Regards,
Ryan

**Comment by magnusviri** [comment]
[p0x, p0y, p0z, p1x, p1y, p1z, ..., pnx, pny, pnz] is exactly it.  Binary is probably best in case of large size but ascii would be nice also (I'm not that great reading binary data, so it would help to have something to verify against).  I'm interested in Legos, so if everything is quantized to Lego brick coordinates the values can be integers.  1 horizontal can be one brick width.  1 vertical can be one plate height.

**Comment by rlguy** [comment]
Hello magnusviri,

I have added an example configuration ([export_particle_positions.h](../blob/master/src/examples/export_particle_positions.h)) for how to use the FluidSimulation class to output fluid particle positions in three forms: as a .ply mesh of vertices, as a binary file, and as a plaintext file. The example file also include methods on how to import the data back into a C++ program.

Is this the kind of data output that you wanted?

Best Regards,
Ryan

**Comment by magnusviri** [comment]
So I'm still grappling to understand this code and what it does and how to use it.  And I guess I should've tried it before I asked for this feature because I think example_lego_sphere_drop.h already does what I want.  And it looks like export_particle_positions.h outputs randomly placed particles within the fluid.  I don't know the ply format though, so I will have to read up on that if I want to do more.

I think before I pursue this more, I should ask one more question.  Can it simulate ocean waves?  I've been working on a Lego boat in the ocean (like in the Lego movie) and I have waves (maybe not the best algorithm but it works) but the missing slash against the boat hull and wake is staring me in the face and I've been trying to rework what I've made so I could try to add those things.  I'm basically hoping that this utility will be able to help, maybe even replace what I've already done.  If this can do ocean waves, I'll probably throw away what I've already done and dive into this a lot more.

**Comment by rlguy** [comment]
Hello magnusviri,

The _example_lego_sphere_drop.h_ sets up a basic 'LEGO' simulation where the output files contain vertex only meshes where a vertex corresponds to the center position of a LEGO brick.

That sounds like a very interesting project that you are working on! This simulation program may not have the required features required for this type of animation. The simulation method is physically based, so it could simulate waves in an ocean while splashing against the hull of a ship, but the simulation is confined to a rectangular grid, so that would mean that the ocean waves would interact with the sides of the fluid domain which may not be desirable. Using a very large domain could help hide the fact that the ocean is interacting with the sides of the domain and give the illusion that the fluid is in a boundless ocean, but could use a very large amount of processing power and memory.

This simulation program also currently lacks the feature of dynamic moving solids. If the ship needs to move, the velocity of the hull would not accurately affect the fluid with its motion.

Let me know if you have any more questions.

Best Regards,
Ryan

**Comment by magnusviri** [comment]
I think I'm going to try to merge my large ocean waves with the splash effect I can get from this utility.  I only work on this a little each week, so I imagine that it will be months before I have anything to show, but I do plan on using this and when it comes time I'll have to figure out how to create a scene.  Anyway, I'm closing it for now and may open a new issue way down the road if I need to.
