### ISSUE TITLE
error: '_hypot' was not declared in this scope {return (float)(_hypot));}

### ISSUE THREAD

**Issue by ivince** [rlguy/GridFluidSim3D#7]
![2016-05-31_215643](https://cloud.githubusercontent.com/assets/12808104/15676910/b6554520-277a-11e6-9ffc-257cd456dc01.png)

**Comment by ivince** [comment]
someone said this is bug in mingw. editing mingw/include/math.h _hypot to hypot solved the issue

**Comment by rlguy** [comment]
Hello ivince,

Good to hear that you were able to find a solution that solves this issue! I'll leave a link to the post describing the fix for anyone else that runs into this error, and close this issue.

[StackOverflow: error: '_hypot' was not declared in this scope](http://stackoverflow.com/a/29489843)

Thanks,
Ryan
