### ISSUE TITLE
error: CL/cl.hpp: No such file or directory #include <CL/cl.hpp>

### ISSUE THREAD

**Issue by ivince** [rlguy/GridFluidSim3D#8]
![2016-05-31_215440](https://cloud.githubusercontent.com/assets/12808104/15677010/fd588ce8-277a-11e6-9f71-9f8256eb8c4d.png)

**Comment by rlguy** [comment]
Hello ivince,

It looks like the OpenCL headers were not found. This could be because the OpenCL header directory is not in your search path or your machine does not have the required _cl.hpp_ header file. What directory are your OpenCL headers in, and does that directory contain the file _cl.hpp_? 

In the case that the OpenCL header directory is not on the search path, you may edit the _OPENCLINCLUDEPATH_ variable in the[Makefile](../blob/master/Makefile) to point to the directory that contains your OpenCL header files.

```
#Example:
OPENCLINCLUDEPATH=-I"path_to_headers"
```

The _-I_ flag will add the _path_to_headers_ directory to the include search path.

In the case that your machine is missing the _cl.hpp_ header, you can download [cl.hpp from khronos.org](https://www.khronos.org/registry/cl/) and place it in the OpenCL header directory. You will need the _cl.hpp_ file version that matches the version of OpenCL on your machine. To find out what version of OpenCL you have, locate the _cl.h_ header and look for largest version number listed under the `/* OpenCL Version */` section.

Let me know if this solves the issue for you.

Best Regards,
Ryan

**Comment by ivince** [comment]
@rlguy i am not solve this issue, my environment is: windows7, nvidia k4000.
i do as follow:  
1. installed MinGW, then installed packages 'g++' and 'make' from MinGW Installation Manager
2. installed nvidia drivers
3. download cuta-toolkit from [https://developer.nvidia.com/cuda-toolkit-31-downloads](https://developer.nvidia.com/cuda-toolkit-31-downloads) and install to the directory "C:\CUDA", which include "include" and "lib" subdirectory
i found directory "C:\CUDA\include\CL" do not include "cl.hpp"
4. so i download openCL 1.2's cl.hpp from [https://www.khronos.org/registry/cl/](https://www.khronos.org/registry/cl/) and move it to "C:\CUDA\include\CL\"
5. edit the project file 'Makefile':

```
OPENCLINCLUDEPATH=-I"C:\CUDA\include"
OPENCLLIBPATH=-L"C:\CUDA\lib"
```

 in the project directory type: mingw32-make
![2016-06-01_123502](https://cloud.githubusercontent.com/assets/12808104/15698251/3f7e8076-27f5-11e6-97fa-c6f43f610b01.png)

can you help me?

**Comment by rlguy** [comment]
Hello ivince,

I have added the _CL_USE_DEPRECATED_OPENCL_1_1_APIS_ declaration to the Makefile in [this commit](https://github.com/rlguy/GridFluidSim3D/commit/b872ef29c5e0d7132c80871f9ff620976b9ec695), which is a fix described in this thread: ["\* has not been declared" when including cl.hpp](https://forums.khronos.org/showthread.php/7931-quot-*-has-not-been-declared-quot-when-including-cl-hpp). 

Let me know if this solves the issue that you are encountering.

Best Regards,
Ryan

**Comment by ivince** [comment]
hello @rlguy,
An error has occurred
![2016-06-02_143701](https://cloud.githubusercontent.com/assets/12808104/15736073/df4998d6-28cf-11e6-973c-2de740212433.png)

**Comment by rlguy** [comment]
Hello ivince,

Sorry to hear that you are still getting errors. I am not sure why this is happening.

 I have only been able to test with OpenCL 1.1 headers. I would suggest trying to replace your _cl.hpp_ file with the 1.1 version instead of 1.2. If the program still give errors like above, try downgrading your OpenCL headers to version 1.1 by replacing the headers in _C:\CUDA\include\CL\_ with the 1.1 versions from [khronos](https://www.khronos.org/registry/cl/). Make sure to backup your current headers before trying this.

Best Regards,
Ryan

**Comment by ivince** [comment]
Hello rlguy,

it make success when i repaced the headers with version 1.1.

thank you
